### PR TITLE
Port to .NET 5

### PR DESCRIPTION
**Pull request by sitiom**
Reopening from #1.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I am seriously contemplating pushing out the .NET 5 version for April Fools Day.  Checked out the updater and it works.

**Comment by Ryochan7** [comment]
Ran into a problem with distribution. The old updater checks in DS4Windows always assumed that the updater was a single exe file. Unfortunately, that is no longer the case with .NET 5. I tried to look into making DS4Updater a self contained app but I cannot get the published program to run properly. Also, the exe file ends up being over 100 MB and it still depends on other DLL files for some reason.

It looks like the next update to DS4Windows will still depend on an updater built with .NET Framework. Going to have to change the distribution method after that point.

**Comment by sitiom** [comment]
> I tried to look into making DS4Updater a self contained app but I cannot get the published program to run properly.

Fixed something about this. Also, I think you are looking for a single app, not a self-contained one.

> Ran into a problem with distribution. The old updater checks in DS4Windows always assumed that the updater was a single exe file. Unfortunately, that is no longer the case with .NET 5. I tried to look into making DS4Updater a self contained app but I cannot get the published program to run properly. Also, the exe file ends up being over 100 MB and it still depends on other DLL files for some reason.

Now that the issue is fixed, the way you can publish a non self-contained, single file app would be something like:
```powershell
dotnet publish -r win-x64 -c Release -p:Platform=x64 -p:PublishSingleFile=true --no-self-contained
```

result

**Comment by sitiom** [comment]
> https://github.com/Ryochan7/DS4Windows/commit/539b4ee1681c6018a519d32c67f26e3de2b42bc2

@Ryochan7 Hmm. I don't think you need to do this anymore as the single file output works well as tested.

**Comment by Ryochan7** [comment]
Thank you for looking into this. I will give that publish command a try in a bit. So the `--no-self-contained` flag is the secret sauce in that command.

No matter what, the DS4Windows update is not getting pushed out today like I hoped. Maybe tomorrow.

**Pull request merged**
